use_frameworks!

platform :ios, '9.0'

target 'HWPGMEKit_Example' do
  pod 'Masonry'

  target 'HWPGMEKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
